import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * Lint configuration.
 *
 * Type-aware rules are on: the ones worth having here — no floating promises,
 * no unsafe `any` flowing out of a GraphQL response — cannot be decided without
 * types, and those are exactly the mistakes this codebase is exposed to.
 *
 * The theme is not linted here. It is Liquid and vanilla JS in Dawn's style,
 * checked by `shopify theme check`, and putting it under a TypeScript-oriented
 * config would produce noise about code this project did not write.
 */
export default tseslint.config(
  {
    ignores: [
      'theme/**',
      '**/dist/**',
      '**/build/**',
      'coverage/**',
      'node_modules/**',
      // Generated by `prisma generate`, not written by anyone.
      'prisma/migrations/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        // Listed explicitly rather than discovered: the browser half has its
        // own config (different lib, different globals), and project discovery
        // would hand those files to the server config that excludes them.
        project: [
          './tsconfig.json',
          './packages/shared/tsconfig.json',
          './apps/admin-app/tsconfig.json',
          './apps/admin-app/tsconfig.web.json',
        ],
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node },
    },
    rules: {
      // An unawaited promise in a request handler is a response that never
      // arrives and an error nothing catches.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      // `_`-prefixed names are the convention for a value that exists only to
      // be destructured away.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Type-only imports are erased at compile time; mixing them with value
      // imports breaks `verbatimModuleSyntax`.
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { fixStyle: 'inline-type-imports' },
      ],
    },
  },

  {
    // Config files are plain JavaScript; type-aware rules have no project to
    // read them from.
    files: ['**/*.js'],
    ...tseslint.configs.disableTypeChecked,
  },

  {
    files: ['apps/admin-app/src/web/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser },
    },
  },

  {
    files: ['**/*.test.ts'],
    rules: {
      // Test doubles stand in for generated Prisma and GraphQL types, and
      // asserting on supertest's `response.body` is untyped by nature.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      // A stub that implements an async interface without awaiting anything is
      // the point of a stub, not an oversight. Same for a `sleep` that records
      // the delay instead of taking it.
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/no-empty-function': 'off',
    },
  },
);
